src/AspNetCore-Mvc-ViewComponents-CoreFx/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore_Mvc_ViewComponents_CoreFx.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/AspNetCore-Mvc-ViewComponents-CoreFx/ViewComponents/AlegriAddressViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore_Mvc_ViewComponents_CoreFx.ViewComponents
{
    public class AlegriAddressViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/AspNetCore-Mvc-ViewComponents-CoreFx/ViewComponents/RandomStringViewComponent.cs
using System.Threading.Tasks;
using AspNetCore_Mvc_ViewComponents_CoreFx.Services;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore_Mvc_ViewComponents_CoreFx.ViewComponents
{
    //[ViewComponent(Name = "RandomString")] // optional
    public class RandomStringViewComponent : ViewComponent
    {
        private readonly IDemoService _demoService;

        public RandomStringViewComponent(IDemoService demoService) // injected by ASP.NET Core built in dependency injection
        {
            _demoService = demoService;
        }

        // !! use InvokeAsync -OR- Invoke


        public async Task<IViewComponentResult> InvokeAsync(int length)
        {
            string randomString = await _demoService.GetRandomStringAsync(length);
            return View("Default", randomString);
        }

        //public IViewComponentResult Invoke(int length)
        //{
        //    string randomString = _demoService.GetRandomString(length);
        //    return View(randomString);
        //}
    }
}

src/AspNetCore-Mvc-ViewComponents-CoreFx/Views/Home/Index.cshtml
@using System.ComponentModel
@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    <div class="col-md-6">
        <h2>View Component Alegri Address</h2>
        @await Component.InvokeAsync("AlegriAddress")
    </div>
    <div class="col-md-6">
        <h2>View Component Random String</h2>
        @await Component.InvokeAsync("RandomString", new { length = 10 })
    </div>
</div>

src/AspNetCore-Mvc-ViewComponents-CoreFx/Views/Shared/Components/AlegriAddress/Default.cshtml
<div class="vcard">
    <p class="fn"><a class="url" href="#">Alegri International Service GmbH - Standort Stuttgart</a><p>
    <p class="adrress">
        <span class="street-address">Meitnerstr. 10</span><br>
        <span class="city-address">70563 Stuttgart</span><br>
    </p>
    <p class="tel">+49 (0)711 68 68 810</p>
</div>

src/AspNetCore-Mvc-ViewComponents-CoreFx/Views/Shared/Components/RandomString/Default.cshtml
@model string
<div class="vcard">
    @Model
</div>

src/AspNetCore-Mvc-ViewComponents-CoreFx/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCore_Mvc_ViewComponents_CoreFx</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCore_Mvc_ViewComponents_CoreFx</a>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - AspNetCore_Mvc_ViewComponents_CoreFx</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>